name: flask-deployment
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: set up python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies # Runs commands using the runners shell
        run: |
          make install

      - name: yamllint with yamllint
        run: |
          sudo apt-get install yamllint
          make yamllint

      - name: Lint with pylint
        run: |
          make lint

      - name: test with pytest
        run: |
          make testapp

      - name: format with yapf
        run: |
          make format

      - name: make a test coverage badge with genbadge
        run: |
          make coverage_badge

      - name: clean pytest report
        run: |
          make cleaning

      - name: Display secret
        run: |
          echo "$HOST_IP"
        env:
          HOST_IP: ${{ secrets.HOST_IP }}

